# Generated by Django 6.0.3 on 2026-04-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='meetup_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
